---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: jenkins-web
  namespace: jenkins
spec:
  virtualhost:
    fqdn: jenkins-np.bcthk.info
    tls:
      secretName: cert-delegation/tls-secret
  routes:
    - conditions:
        - prefix: /
      services:
        - name: jenkins
          port: 8080

 
